CMAKE_MINIMUM_REQUIRED(VERSION 3.20)

PROJECT(UniversalVision)

SET(CMAKE_CXX_STANDARD 17)
SET(CMAKE_CXX_STANDARD_REQUIRED ON)
SET(CMAKE_CXX_EXTENSIONS OFF)

MESSAGE(STATUS "Project ${PROJECT_NAME} build in: ${BUILD_DIR}, ${CMAKE_BUILD_TYPE}")

IF(CMAKE_BUILD_TYPE STREQUAL "Debug")
    ADD_DEFINITIONS(-DDEBUG)
ELSE()
    ADD_DEFINITIONS(-DNDEBUG -DRELEASE)
ENDIF()


IF(MSVC)
    # ON /MD dynamic, /MT static

    # Static runtime
    # SET(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CMAKE_BUILD_TYPE:Debug>:Debug>")

    # Dynamic runtime
    # SET(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreadedDLL$<$<CMAKE_BUILD_TYPE:Debug>:Debug>")

    IF(CMAKE_BUILD_TYPE STREQUAL "Debug")
        SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /MDd")
    ELSE()
        SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /MD")
    ENDIF()

    # For boost::throw_exception
    SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /EHsc")
ENDIF(MSVC)

INCLUDE_DIRECTORIES(${PROJECT_SOURCE_DIR})

# Boost
SET(CMAKE_PREFIX_PATH "${CMAKE_PREFIX_PATH};${BOOST_CMAKE_PACKAGE_PATH}")
# Recommend to use dynamic runtime
SET(Boost_USE_STATIC_RUNTIME OFF)
SET(Boost_USE_STATIC_LIBS ON)
IF (CMAKE_BUILD_TYPE STREQUAL "Debug")
    SET(Boost_USE_DEBUG_LIBS ON)
ELSE()
    SET(Boost_USE_DEBUG_LIBS OFF)
ENDIF()
find_package(Boost COMPONENTS REQUIRED log log_setup date_time filesystem thread system exception atomic)
MESSAGE(STATUS "Boost_DIR: ${Boost_DIR}")
MESSAGE(STATUS "Boost_INCLUDE_DIR: ${Boost_INCLUDE_DIR}")
MESSAGE(STATUS "Boost_LIBRARIES: ${Boost_LIBRARIES}")
INCLUDE_DIRECTORIES(${Boost_INCLUDE_DIR})

# Poco
SET(CMAKE_PREFIX_PATH "${CMAKE_PREFIX_PATH};${POCO_CMAKE_PACKAGE_PATH}")
find_package(Poco COMPONENTS REQUIRED Foundation)
MESSAGE(STATUS "Poco_DIR: ${Poco_DIR}")
MESSAGE(STATUS "Poco_INCLUDE_DIR: ${Poco_INCLUDE_DIR}")
MESSAGE(STATUS "Poco_LIBRARIES: ${Poco_LIBRARIES}")


MESSAGE(STATUS "CMAKE_PREFIX_PATH: ${CMAKE_PREFIX_PATH}")


# LOG
IF(ENABLE_BOOST_LOG)
    MESSAGE(STATUS "Enable Boost log")
    ADD_DEFINITIONS(-DENABLE_BOOST_LOG)
    # SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DENABLE_BOOST_LOG")
ELSEIF(ENABLE_POCO_LOG)
    MESSAGE(STATUS "Enable Poco log")
    ADD_DEFINITIONS(-DENABLE_POCO_LOG)
    # SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DENABLE_POCO_LOG")
ENDIF()

ADD_SUBDIRECTORY(base)
ADD_SUBDIRECTORY(app)

IF(ENABLE_TEST)
    MESSAGE(STATUS "Enable test")
    SET(CMAKE_PREFIX_PATH "${CMAKE_PREFIX_PATH};${GTEST_CMAKE_PACKAGE_PATH}")
    find_package(GTest REQUIRED)
    MESSAGE(STATUS "GTEST_LIBRARIES: ${GTEST_LIBRARIES}")
    MESSAGE(STATUS "GTEST_MAIN_LIBRARIES: ${GTEST_MAIN_LIBRARIES}")
    ADD_SUBDIRECTORY(test)
ENDIF()