# glad
FILE(GLOB SRC ${CMAKE_SOURCE_DIR}/third_party/glad/src/*.c)

LIST(APPEND SRC ${CMAKE_CURRENT_SOURCE_DIR}/src/main.cpp)

INCLUDE_DIRECTORIES(${GLFW_INCLUDE_PATH}
                    ${CMAKE_SOURCE_DIR}/third_party/glad/include)

LIST(APPEND APP_SRC ${CMAKE_CURRENT_SOURCE_DIR}/src/application.cpp)

FILE(GLOB APP_INC ${CMAKE_CURRENT_SOURCE_DIR}/inc/*.h)

INCLUDE_DIRECTORIES(${CMAKE_CURRENT_SOURCE_DIR}/inc)

ADD_LIBRARY(app STATIC ${APP_SRC} ${APP_INC})

ADD_EXECUTABLE(${PROJECT_NAME} ${SRC} ${INC})

# SOURCE_GROUP("src" FILES ${SRC})
# SOURCE_GROUP("inc" FILES ${INC})

TARGET_LINK_LIBRARIES(${PROJECT_NAME} app ${GLFW_LIB_PATH}/glfw3.lib opengl32.lib base)

SET_TARGET_PROPERTIES(app PROPERTIES FOLDER "app")